# Cotire.cmake 1.8.0 generated file
# /home/finley/CODE/MVS/openMVS_build_clion/libs/Common/Common_CXX_Cotire.cmake
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_EXTENSIONS "inc;inl;ipp")
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_PATH "")
set (COTIRE_CLEAN_ALL_TARGET_NAME "clean_cotire")
set (COTIRE_CLEAN_TARGET_SUFFIX "_clean_cotire")
set (COTIRE_CMAKE_MODULE_FILE "/home/finley/CODE/MVS/openMVS/build/Cotire.cmake")
set (COTIRE_CMAKE_MODULE_VERSION "1.8.0")
set (COTIRE_DEBUG "OFF")
set (COTIRE_INTDIR "cotire")
set (COTIRE_MAXIMUM_NUMBER_OF_UNITY_INCLUDES "0")
set (COTIRE_MINIMUM_NUMBER_OF_TARGET_SOURCES "2")
set (COTIRE_PCH_ALL_TARGET_NAME "all_pch")
set (COTIRE_PCH_TARGET_SUFFIX "_pch")
set (COTIRE_PREFIX_HEADER_FILENAME_SUFFIX "_prefix")
set (COTIRE_TARGETS_FOLDER "CMakeTargets")
set (COTIRE_TARGET_COMPILE_DEFINITIONS_RELEASE "_USE_OPENMP;_USE_OPENGL;_USE_BOOST;_USE_EIGEN;_USE_NONFREE;_USE_FAST_FLOAT2INT;_USE_FAST_CBRT;_USE_SSE;_LIB;NDEBUG")
set (COTIRE_TARGET_COMPILE_FLAGS_RELEASE "-W;-Wall;-Werror=address;-Werror=sequence-point;-Wformat;-Werror=format-security;-Winit-self;-Wsign-promo;-Wreorder;-Wno-undef;-Wno-switch;-Wno-switch-enum;-Wno-switch-default;-Wno-implicit-fallthrough;-Wno-comment;-Wno-narrowing;-Wno-attributes;-Wno-ignored-attributes;-Wno-maybe-uninitialized;-Wno-enum-compare;-Wno-misleading-indentation;-Wno-missing-field-initializers;-Wno-unused-result;-Wno-unused-function;-Wno-unused-parameter;-Wno-delete-incomplete;-Wno-int-in-bool-context;-fdiagnostics-show-option;-ftemplate-backtrace-limit=0;-Wno-long-long;-pthread;-fomit-frame-pointer;-frounding-math;-msse;-msse2;-msse3;-mssse3;-msse4.1;-msse4.2;-ffunction-sections;-fopenmp;-O3;-W;-Wall;-Werror=address;-Werror=sequence-point;-Wformat;-Werror=format-security;-Winit-self;-Wsign-promo;-Wreorder;-Wno-undef;-Wno-switch;-Wno-switch-enum;-Wno-switch-default;-Wno-implicit-fallthrough;-Wno-comment;-Wno-narrowing;-Wno-attributes;-Wno-ignored-attributes;-Wno-maybe-uninitialized;-Wno-enum-compare;-Wno-misleading-indentation;-Wno-missing-field-initializers;-Wno-unused-result;-Wno-unused-function;-Wno-unused-parameter;-Wno-delete-incomplete;-Wno-int-in-bool-context;-fdiagnostics-show-option;-ftemplate-backtrace-limit=0;-Wno-long-long;-pthread;-fomit-frame-pointer;-frounding-math;-msse;-msse2;-msse3;-mssse3;-msse4.1;-msse4.2;-ffunction-sections;-Wall;-fexceptions;-std=c++14")
set (COTIRE_TARGET_CONFIGURATION_TYPES "Release")
set (COTIRE_TARGET_CXX_COMPILER_LAUNCHER "COTIRE_TARGET_CXX_COMPILER_LAUNCHER-NOTFOUND")
set (COTIRE_TARGET_IGNORE_PATH "/home/finley/CODE/MVS/openMVS;/home/finley/CODE/MVS/openMVS_build_clion")
set (COTIRE_TARGET_INCLUDE_DIRECTORIES_RELEASE "/home/finley/CODE/MVS/openMVS;/usr/include/eigen3;/usr/local/include/opencv4")
set (COTIRE_TARGET_INCLUDE_PRIORITY_PATH "")
set (COTIRE_TARGET_LANGUAGE "CXX")
set (COTIRE_TARGET_MAXIMUM_NUMBER_OF_INCLUDES "")
set (COTIRE_TARGET_POST_UNDEFS "")
set (COTIRE_TARGET_PRE_UNDEFS "")
set (COTIRE_TARGET_SOURCES "/home/finley/CODE/MVS/openMVS/libs/Common/Common.cpp;/home/finley/CODE/MVS/openMVS/libs/Common/CUDA.cpp;/home/finley/CODE/MVS/openMVS/libs/Common/ConfigTable.cpp;/home/finley/CODE/MVS/openMVS/libs/Common/EventQueue.cpp;/home/finley/CODE/MVS/openMVS/libs/Common/Log.cpp;/home/finley/CODE/MVS/openMVS/libs/Common/SML.cpp;/home/finley/CODE/MVS/openMVS/libs/Common/Timer.cpp;/home/finley/CODE/MVS/openMVS/libs/Common/Types.cpp;/home/finley/CODE/MVS/openMVS/libs/Common/Util.cpp")
set (COTIRE_UNITY_BUILD_ALL_TARGET_NAME "all_unity")
set (COTIRE_UNITY_BUILD_TARGET_SUFFIX "_unity")
set (COTIRE_UNITY_OUTPUT_DIRECTORY "")
set (COTIRE_UNITY_SOURCE_EXCLUDE_EXTENSIONS "m;mm")
set (COTIRE_UNITY_SOURCE_FILENAME_SUFFIX "_unity")
set (CMAKE_GENERATOR "Unix Makefiles")
set (CMAKE_BUILD_TYPE "Release")
set (CMAKE_CXX_COMPILER_ID "GNU")
set (CMAKE_CXX_COMPILER_VERSION "7.5.0")
set (CMAKE_CXX_COMPILER "/usr/bin/c++")
set (CMAKE_CXX_COMPILER_ARG1 "")
set (CMAKE_INCLUDE_FLAG_CXX "-I")
set (CMAKE_INCLUDE_SYSTEM_FLAG_CXX "-isystem ")
set (CMAKE_CXX_SOURCE_FILE_EXTENSIONS "C;M;c++;cc;cpp;cxx;mm;mpp;CPP")
